config:
  title: WEB-ADMIN-PRO
  version: 1.0.0
  copyright: © 2026 All Rights Reserved.

server:
  port: 80

spring:
  application:
    name: ${config.title}
    version: ${config.version}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web-admin-pro
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  session:
    jdbc:
      initialize-schema: always
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

logging:
  level:
    com.admin.web: info
  file:
    name: logs/web-admin-pro.log